CREATE TABLE USERS(
    USERID number(6) NOT NULL,
    EMAIL VARCHAR2(50),
    PASS VARCHAR2(50),
    FIRSTNAME NVARCHAR2(50),
    LASTNAME NVARCHAR2(50),
    PRIMARY KEY (USERID)
);
INSERT INTO "ITSOL"."USERS" (USERID, EMAIL, PASS, FIRSTNAME, LASTNAME) VALUES ('1', 'tuan@gmail.com', '1234', 'nguyen', 'tuan');
INSERT INTO "ITSOL"."USERS" (USERID, EMAIL, PASS, FIRSTNAME, LASTNAME) VALUES ('2', 'long@gmail.com', '1234', 'nguyen', 'long');
SELECT USERID, EMAIL, PASS, FIRSTNAME, LASTNAME FROM ITSOL.USERS WHERE EMAIL = 'tuan@gmail.com' AND PASS = '1234';
